### ISSUE TITLE
Non-fatal test failure?

### ISSUE THREAD

**Issue by Krinkle** [glayzzle/php-runtime#3]
<https://travis-ci.org/glayzzle/php-runtime> shows:

<img width="788" alt="screen shot 2017-07-31 at 21 19 41" src="https://user-images.githubusercontent.com/156867/28809111-fc8cd458-7635-11e7-86bd-3f9f99c1007c.png">

Just passing by, but figured I'd let you know in case this is not intended.

**Comment by ichiriac** [comment]
haha :) https://github.com/glayzzle/php-runtime/blob/master/src/ext/constants.js#L71

Thanks @Krinkle, indeed it's an syntax error triggered by istanbul (code coverage tool) but as I don't yet use this file so did not paid attention on it.

I'll fix it later, the project is paused / almost dead.

BTW, if you're interested in this kind of stuff, take a look at this library, it's more advanced : https://gitlab.com/kornelski/babel-preset-php
